let value: string | number;
value = "Hello";
console.log(`Value as string: ${value}`);
value = 42;
console.log(`Value as number: ${value}`);
let status: "enable" | "disable";
status = "enable";
console.log(`Status: ${status}`);
status = "disable";
console.log(`Status: ${status}`);
